### ISSUE TITLE
Modify frontend to use JSON sent by GetSessionDiagram servlet correctly

### ISSUE THREAD

**Issue by tomasSimandl** [ReliSA/IMiGEr#10] opened 2018-11-23 10:40 UTC
It is possible that data.attributeTypes is in input JSON empty for example when no attributes are needed in vertices and edges. 

![image](https://user-images.githubusercontent.com/16165127/48939437-85ebaf00-ef14-11e8-9443-1c376eaeee88.png)

**Comment by fidransky** [comment] 2018-12-03 02:11
@tomasSimandl, this actually works correctly. The cause is that you changed JSON format sent from `GetSessionDiagram` in commit 72b9be1.

**Comment by tomasSimandl** [comment] 2018-12-03 05:58
@fidransky, still not working. Referenced commit was created after this issue. For error reproduce you can use file: src\test\resources\data\RawAssociatedArchetypeTest.json

**Comment by fidransky** [comment] 2018-12-03 09:00
Ah, okay. We need to agree on which keys are obligatory in the JSON. I made it so that these are required:

* **attributeTypes** - min 1 item, unique
* **edgeArchetypes** - min 1 item, unique
* **vertexArchetypes** - min 1, item unique
* **vertices** - min 1 item, unique
* **edges** - min 1 item, unique
* **possibleEnumValues**
* **groups** - unique
* **sideBar** - unique
* **highlightedVertex**
* **highlightedEdge**

My intent was to make is as strict as possible but I probably dont see all usecases as you do. The check itself is performed against JSON Schema - [src/main/webapp/imiger-raw-input-schema.json](../blob/master/sources/src/main/webapp/imiger-raw-input-schema.json).

Please, think about what keys should be obligatory. IMO, it's only *vertices* and *edges*.

**Comment by pbrada** [comment] 2018-12-03 15:54
My view: IF undefined Types/Archetypes can be handled gracefully, then I would opt for "only _vertices_ and _edges_ are mandatory" as @fidransky suggests.  ELSE, the first 5 items should be mandatory.

**Comment by tomasSimandl** [comment] 2018-12-03 16:08
When Types/Archetypes will not be defined no archetype icon will be visible and functionality of filter will be limited but this will not be fixed by one attributeType, edgeArchetype and vertexArchetype. My opinion is that only vertices and edges should be mandatory.

**Comment by pbrada** [comment] 2018-12-05 21:01
> When Types/Archetypes will not be defined no archetype icon will be visible and functionality of filter will be limited but this will not be fixed by one attributeType, edgeArchetype and vertexArchetype. (...)

The first part (no icon visible) is OK from "graceful handling" PoV.

In what way will filters be limited?  No filter by the missing archetypes?  This would also be OK, as far as I am concerned.

**Comment by fidransky** [comment] 2018-12-19 07:08
I made it so that only *vertices* and *edges* are required in input data. Closing.

**Closed by fidransky** 2018-12-19 07:08 UTC
Labels: bug
